<?php include 'header.php';?>
<p>Loose TEA Music Theatre, an indie opera company in Toronto, was founded in 2013 by our Artistic Director Alaina Viau and was officially incorporated as a Federal Not For Profit Corporation in February 2014. Loose TEA was granted charitable status by the CRA in February of 2016. Loose TEA is fortunate to have an active Board of Directors with over 65 years of experience in the field of theater and music. 
<p>It is the mission of Loose TEA Music Theatre to take classical musical and operatic works and entrench them with the issues, concerns and topics of our present day world. We do this by retaining the music of the original works but rework the original story so that it resonates with issues of today, by creating a new English libretto, and add additional dialogue in order to allow for greater character development. This creates a new form of opera that we call a opera/theatre hybrid. It is our intent to challenge, motivate, and inspire our audience through the mediums of music, opera and theatre in a way that is approachable, understandable and relevant. Loose TEA is an opera company for the 21st century that is followed by a new generation of opera goers.
<p>Our inaugural production in August 2013 was a re-working of the famous Carmen by Bizet. In this version, the story was reduced from 3 hours to 1 while rearranging the story to correspond to the original novella plot. This production was not in the vein of the Loose TEA model in that it was in the original French language with surtitles.
<p>Our 2nd production, in August 2014, was entitled "Love in the Age of Autocorrect" featuring a double bill of Mozart's Bastien und Bastienne (renamed Andrew and Andrea) and Stravinsky's Mavra. Both comedies were translated into modern English and set in current times to comment on how the digital world affects our interpersonal relationships. 
<p>Our most recent production, presented in August of 2015, titled "Dissociative Me" was a re-imagined version of Gounod's "Faust". This production dealt with mental health issues, specifically Dissociative Personality Disorder. In this unique work Mephistopheles was an alternate personality of our Dr. Faust.  In June of 2015, we re-staged "Andrew and Andrea" in in the Proof Lounge of the Intercontinental Hotel in Toronto for guests of the hotel and a "Meet Up" event. In early 2015 Loose TEA was selected to be one of ten companies to participate in the LEAN Arts program in Toronto. This 8 week workshop was created to enable arts organizations to think like high tech start ups and apply some of those principles to small arts organizations.
<p>In 2016, so far, we have been selected to participate in the 37th annual Rhubarb Festival held at Buddies in Bad Times Theatre in Toronto. We will be presenting "Trance Symphony No.5" that is a re-creation of Beethoven's 5th symphony for Trance DJ artist and 14 live musicians. In early Summer of 2016 we will be again holding our "Whose Opera is it Anyway? " fundraiser.

<h2>ALAINA VIAU, Artistic Director and Stage Director</h2>

<p>Alaina is an opera stage director, conductor and production manager based out of Toronto. She is the founder and Artistic Director of indie opera company Loose TEA Music Theatre. With them she has directed and trans-adapted Dissociative Me (Gounod), Love in the Age of AutoCorrect (Mozart/Stravinsky) and La Tragedie de Carmen(Bizet). Currently the company is working on a new version of the Carmen story, a #blacklivesmatter inspired Tosca (Puccini) and a new full length opera to be premiered in 2018. Loose TEA has been shortlisted for the Rhubarb Festival 2016 with Buddies in Bad Times Theatre with our orchestra concept piece, Trance Symphony No.5, which is a Trance/Classical Dance experience of Beethoven's popular Symphony no.5 with live orchestra and trace DJ.
<p>This year Alaina is assistant director for Joel Ivany at the Canadian Opera Company with Carmen, and a staged Mozart's Requiem with the Toronto Symphony Orchestra.  She has apprenticed with Atom Egoyan at the COC's Die Walkure (Wagner) in 2015. Alaina has also assisted Ashlie Corcoran at the Royal Conservatory of Music with Don Giovanni(Mozart) in 2013. Prior to moving to Toronto in 2012, Alaina directed Le Nozze di Figaro (Mozart) in London UK, Into the Woods (Sondheim) and Annie (Strouse/Charnin) in Ottawa.
<p>As a conductor, Alaina spent all of 2014 studying the symphonies of Beethoven and leading concerts of all nine symphonies with the Glenn Gould School Student Orchestra . At the Royal Conservatory of Music, Alaina assisted Lior Shambadal (Beethoven 3), Uri Mayer (Brahms 1) and with Orchestra Toronto under Kevin Mallon (Brahms 1). Alaina apprenticed on the Glenn Gould School Operas with Uri Mayer on The Cunning Little Vixen (Janacek),  and La Belle Helene (Offenbach). With Christopher Mokrzewski, Alaina has assistant conducted their ATG Messiah in 2013 and is excited to do so again in Dec 2015.  While working with Atom Egoyan on Die Walkure, Alaina worked double duty and also apprentice conducted with Johannes Debus. She looks forward to apprenticing with him again at the COC on Sigfreid (Wagner).
<p>Alaina currently works with the Toronto Symphony Orchestra as their Assistant Production Manager and previously worked for the Glenn Gould School as the Orchestra and Opera Manager. 

<h2>MARKUS KOPP, General Manager and Producer</h2>

<p>As a strong advocate for the performing arts, Mr. Kopp joined Loose TEA Music Theatre after its production in 2013. He has over 25 years of experience in the hi-tech sector as an engineer and director. Mr. Kopp has been instrumental in moving Loose Tea away from the traditional arts business model and adopting the practises and strategies that are applied to hi-tech start-up companies. He provides Loose TEA with a clear business vision and direction with the long term aim of creating a self-sustaining opera company. Not a stranger to the stage, Mr. Kopp was a stage actor for many years while living in the USA prior to moving to Canada in 2002.

<h2>AISLINN RITCHIE, Stage Manager</h2>

<p>Select stage management credits for Aislinn Ritchie include Of a Monstrous Child: a gaga musical (Ecce Homo and Buddies in Bad Times), Catalpa (Blood in the Alley), Cryptomnesia (Fawn Opera), Postcards from Morocco (ASM), Don Giovanni (ASM), Le Laureat, Three Sisters Who Are Not Sisters, and The Magic Flute (Royal Conservatory of Music), La Boheme (Against the Grain Theatre), Don Giovanni, and La Traviata, (COSI). She has production managed La Tragedie de Carmen (Loose Tea Music Theatre), and the Synesthesia series with Fawn Opera. She apprenticed with Thousand Islands Playhouse on Henry & Alice: Into the Wild, with CCOC on Laura's Cow, with Queen of Puddings on Svadba-Wedding, with COC on Carmen, and with Chemainus Theatre Festival on Lost in Yonkers, A Child's Christmas in Wales, A Perfect Wife, and Munsch Alley. With Randolph Academy for the Performing Arts she stage managed Hair, Provenance, Little Women, The Pajama Game, The Wiz, Urinetown, Into the Woods, Anne of Green Gables, and A Chorus Line.

<?php include 'footer.php';?>